# Numpy
1. 功能
    - 快速多維陣列操作
    - 科學功能函數庫
    - 協助繪圖工具繪圖
2. 提供以向量化形式的快速 N-d 陣列類型供操作
3. 核心功能是陣列物件類別
4. 陣列類似list,但陣列裡的元素必是相同類型
5. list不能直接使用算術運算工具(+,-,*,/,...)
6. 提供更有效率的計算與多維運算工具

In [1]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [2]:
%time for _ in range(10): my_arr2 = my_arr * 2

CPU times: total: 0 ns
Wall time: 14 ms


In [3]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: total: 406 ms
Wall time: 493 ms


list -> 一般陣列

In [4]:
a = [1, 3, 5, 7, 9]
print(a[2:4])  # 輸出a[2]-a[3]

b = [[1, 3, 5, 7, 9], [2, 4, 6, 8, 10]]
print(b[0])
print(b[1][2:4])

c = [1, 3, 5, 7, 9]
d = [3, 5, 6, 7, 9]
f = c+d
print(f)
print(type(a), type(b), type(c), type(d))

[5, 7]
[1, 3, 5, 7, 9]
[6, 8]
[1, 3, 5, 7, 9, 3, 5, 6, 7, 9]
<class 'list'> <class 'list'> <class 'list'> <class 'list'>


# Numpy陣列
### 一維陣列
![一維陣列](./1d.png)
### 二維陣列
![二維陣列](./2d.png)
### 三維陣列
![三維陣列](./3d.png)

##### list -> ndarray
1. [1, 2, 3]是一維陣列, index:3
2. [[1, 0, 0], [0, 1, 2]]是二維陣列, 第一維index:2, 第二維index:3
3. Numpy陣列被稱為ndarray
4. 透過array方法將list轉為ndarray

In [5]:
a = np.array([1, 3, 5, 7, 9])
b = np.array([3, 5, 6, 7, 9])
c=a+b
print(c)
print("------------------")
c=a-b
print(c)
print("------------------")
print(type(c))

[ 4  8 11 14 18]
------------------
[-2 -2 -1  0  0]
------------------
<class 'numpy.ndarray'>


## Numpy建立與計算
- Numpy的ndarray放的都是相同的資料類型
- ndarray是多維度陣列,提供以陣列為導向的快速算術運算和有彈性的廣播(Broadcast
)能力
    - 廣播(Broadcast)
        - 單一數字 
            - 將原本陣列所有元素根據運算式加減乘除廣播的數字，產生新的陣列
        ![broadcast1](./broadcast1.png)
        - 陣列
            - 將一陣列廣播到另一陣列，透過運算式計算後廣播，但須注意同一維度的數量必須相等或等於1，不然廣播會錯誤
            - 如果相同尺寸陣列，廣播就將同位置元素互相計算，得到最終結果
        ![broadcast2](./broadcast2.png)
- ndarray提供在整個陣列的數學運算不需使用python的迴圈功能
- 線代,亂數,傅立葉轉換
- 提供由c,c++,FORTRAN的資料庫
### 陣列初始與規劃
1. 陣列初始化
2. 陣列重新規劃
3. 計算與取代
### 指定與重設
1. 一個整數指定
2. tuple或list指定
3. 重設陣列
### 數值計算與處理
1. 數值計算
2. 總和最大與最小
3. 中位數與平均
### NP陣列基本屬性
1. ndarray.ndim  - 維度數量
2. ndarray.shape - 顯示出陣列在每個維度上的整數值
3. ndarray.size  - 陣列內元素的總數
4. ndarray.dtype - 來描述陣列中元素類型的對象 

Broadcast

In [6]:
a = np.array([1, 2, 3, 4])
b = np.sum(a)
print(a + b)  # [11 12 13 14]
print(a - b)  # [-9 -8 -7 -6]
print(a * b)  # [10 20 30 40]
print(a % b, end='\n\n')  # [1 2 3 4]

c = np.array([[1, 2, 3], [4, 5, 6]])
d = 2
print(c + d)  # [[3 4 5] [6 7 8]]
print(c - d)  # [[-1  0  1] [ 2  3  4]]
print(c * d)  # [[ 2  4  6] [ 8 10 12]]
print(c % d)  # [[1 0 1] [0 1 0]]

[11 12 13 14]
[-9 -8 -7 -6]
[10 20 30 40]
[1 2 3 4]

[[3 4 5]
 [6 7 8]]
[[-1  0  1]
 [ 2  3  4]]
[[ 2  4  6]
 [ 8 10 12]]
[[1 0 1]
 [0 1 0]]


In [7]:
a = np.array([[1, 1, 1], [2, 2, 2]])
b = np.array([1, 2, 3])
print(a+b)  # [[2 3 4] [3 4 5]]
print(a-b)  # [[ 0 -1 -2] [ 1  0 -1]]
print(a*b)  # [[1 2 3] [2 4 6]]
print(a%b,end='\n\n')  # [[0 1 1] [0 0 2]]

c = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
d = np.array([[1], [2], [3]])
print(c+d)  # [[2 2 2] [4 4 4] [6 6 6]]
print(c-d)  # [[0 0 0] [0 0 0] [0 0 0]]
print(c*d)  # [[1 1 1] [4 4 4] [9 9 9]]
print(c%d)  # [[0 0 0] [0 0 0] [0 0 0]]

[[2 3 4]
 [3 4 5]]
[[ 0 -1 -2]
 [ 1  0 -1]]
[[1 2 3]
 [2 4 6]]
[[0 1 1]
 [0 0 2]]

[[2 2 2]
 [4 4 4]
 [6 6 6]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [4 4 4]
 [9 9 9]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


ndArray

In [8]:
# 建立50位學生的中文和英文的分數
import random
chinese = [random.randint(60, 100) for _ in range(50)]
english = [random.randint(60, 100) for _ in range(50)]

print(f'chinese:{chinese}')
print(f'english:{english}')

chinese:[93, 93, 82, 63, 98, 73, 94, 60, 78, 80, 90, 66, 65, 66, 79, 73, 88, 79, 98, 96, 63, 69, 60, 67, 65, 86, 73, 66, 96, 82, 74, 78, 61, 68, 78, 62, 62, 83, 69, 66, 85, 85, 87, 100, 72, 80, 75, 65, 84, 93]
english:[81, 62, 95, 99, 77, 83, 63, 69, 85, 76, 65, 65, 79, 81, 73, 74, 72, 66, 96, 85, 94, 71, 61, 86, 95, 77, 67, 96, 64, 61, 70, 94, 86, 79, 62, 88, 66, 84, 100, 63, 65, 88, 93, 79, 98, 95, 60, 78, 75, 97]


In [9]:
# 中文和英文的總和
result = []
for i in range(50):
    total = chinese[i] + english[i]  # ex:chinese[1]+english[1]
    result.append(total)  # total加到list裡面
print(result)

#利用comprehension來建立中文和英文的總和
result = [chinese[i]+english[i] for i in range(50)]
result

[174, 155, 177, 162, 175, 156, 157, 129, 163, 156, 155, 131, 144, 147, 152, 147, 160, 145, 194, 181, 157, 140, 121, 153, 160, 163, 140, 162, 160, 143, 144, 172, 147, 147, 140, 150, 128, 167, 169, 129, 150, 173, 180, 179, 170, 175, 135, 143, 159, 190]


[174,
 155,
 177,
 162,
 175,
 156,
 157,
 129,
 163,
 156,
 155,
 131,
 144,
 147,
 152,
 147,
 160,
 145,
 194,
 181,
 157,
 140,
 121,
 153,
 160,
 163,
 140,
 162,
 160,
 143,
 144,
 172,
 147,
 147,
 140,
 150,
 128,
 167,
 169,
 129,
 150,
 173,
 180,
 179,
 170,
 175,
 135,
 143,
 159,
 190]

In [10]:
# numpy可以陣列和陣列做運算
ndChinese = np.array(chinese)
print(ndChinese.__class__)
print(ndChinese)
ndEnglish = np.array(english)
print(ndEnglish.__class__)
print(ndEnglish)
print(ndChinese+ndEnglish)

<class 'numpy.ndarray'>
[ 93  93  82  63  98  73  94  60  78  80  90  66  65  66  79  73  88  79
  98  96  63  69  60  67  65  86  73  66  96  82  74  78  61  68  78  62
  62  83  69  66  85  85  87 100  72  80  75  65  84  93]
<class 'numpy.ndarray'>
[ 81  62  95  99  77  83  63  69  85  76  65  65  79  81  73  74  72  66
  96  85  94  71  61  86  95  77  67  96  64  61  70  94  86  79  62  88
  66  84 100  63  65  88  93  79  98  95  60  78  75  97]
[174 155 177 162 175 156 157 129 163 156 155 131 144 147 152 147 160 145
 194 181 157 140 121 153 160 163 140 162 160 143 144 172 147 147 140 150
 128 167 169 129 150 173 180 179 170 175 135 143 159 190]


使用array function 建立ndarray

In [11]:
# 不要使用from numpy import *,容易和其他module衝突,例如(max,min)
# np.array(任何的串列資料)

l = [[1, 2, 3], [2, 3, 4]]
a = np.array(l)
a  #array([[1, 2, 3],[2, 3, 4]])

print(a.ndim)   # 維度
print(a.shape)  # 形狀
print(a.size)   # 總元素數量
a.dtype         # ndarray的資料型別

2
(2, 3)
6


dtype('int32')

In [14]:
# 產生亂數陣列
data = np.random.randn(2, 3)  # 產生一2x3陣列  # randn產生符合常態分佈的亂數
data

array([[ 0.57422944, -0.69033685, -0.51799289],
       [-1.99913863, -1.1341877 , -0.12644057]])

In [17]:
# 數學運算
data * 10

array([[  5.74229436,  -6.90336852,  -5.1799289 ],
       [-19.99138632, -11.34187703,  -1.26440571]])

In [18]:
data += data  # 每個值自己加自己
data

array([[ 1.14845887, -1.3806737 , -1.03598578],
       [-3.99827726, -2.26837541, -0.25288114]])

In [19]:
# 每個陣列都有shape,使用tuple來表示每個維度的大小
data.shape

(2, 3)

In [20]:
# 使用dtype屬性來顯示目前陣列內的資料型態(相同型態)
data.dtype

dtype('float64')

In [22]:
# 建立一維ndarray
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [25]:
# 建立二維ndarray
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [26]:
# ndim屬性查詢維度
arr2.ndim

2

In [27]:
# shape查詢每個維度大小
arr2.shape

(2, 4)

In [28]:
arr1.dtype

dtype('float64')

In [29]:
arr2.dtype

dtype('int32')

In [36]:
# 使用ones(),zeros(),empty(),arange()function建立ndarray
np.zeros(10)  # 建立一維矩陣,內容為10個0
"""
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
"""
np.zeros((3, 6))
"""
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])
"""
np.empty((2, 3, 2))  # value都是garbage  # value為隨機值(未初始化,可能為任意值)


array([[[8.51767459e-312, 2.96439388e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.06099790e-312, 1.50008929e+248]],

       [[4.31174539e-096, 1.15998412e-028],
        [3.77778426e+180, 1.15998412e-028],
        [4.19462329e+228, 1.55535091e+161]]])

In [37]:
# 使用arange()function建立,類似於python range()
np.arange(15)  # 0-14

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])